### ISSUE TITLE
Using chatu on windows

### ISSUE THREAD

**Issue by hkoschitzki** [kimim/chatu#2]
Hi,
thanks for this very useful software. Unfortunately I have to use Windows at work, but chatu did not work out of the box. I got it working  to convert drawio images after I changed chatu-drawio.el:
1. I removed all "> /dev/null ">&1"  from the script calls.
2. I changed (funcall chatu-drawio-executable-func) to  (shell-quote-argument (funcall chatu-drawio-executable-func)) because drawio.exe is located in "C:\Program Files".

It would be nice, if you could provide a more generalized solution to support Windows as well.

Thanks

**Comment by kimim** [comment]
Thanks for the issue. Actually, I, myself, is using Emacs in Windows, but distributed by msys64.
I changed the code according to your suggestions now. 
If you are using `chatu-mode` from melpa, you may need to wait 1 day for it to be synchronized to downstream repo.

**Comment by kimim** [comment]
If everything works fine, I'll close this issue. Thanks.

**Comment by hkoschitzki** [comment]
Hi,

I updated from Melpa and everything works fine.

Thanks
