### ISSUE TITLE
建议：改改名字

### ISSUE THREAD

**Issue by yibie** [kimim/chatu#3]
chatu 是完整的中国拼音，其实老外不知道这个插件是干嘛的。
建议改一改名字，让它更加跟国际接轨。

**Comment by kimim** [comment]
We have one PR from Scotland Scottish developer. Non-Chinese speakers might be willing to learn Chinese?

**Comment by kimim** [comment]
Renaming is quite a nontrivial task, we need to change the repo name, names in elisp code and package name in elpa.
So I propose to keep the name. Sorry.

**Comment by yibie** [comment]
虽然不知道您为啥要用英文回答一个中文问题，但又坚持用一个中文拼音来为插件命名，只能回一句，您喜欢就好，是我多事了。

**Comment by kimim** [comment]
其实一个名字无所谓的。不认识的人，让他看下说明，也就知道什么意思。顺便推广下中文么，你说怎么样。
